version: '3'
services:
  python-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
          # Update 'VARIANT' to pick a Python version: 3, 3.6, 3.7, 3.8, 3.9
          VARIANT: 3.8
          # Options
          INSTALL_NODE: "true"
          NODE_VERSION: "lts/*"
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
